class EmailFlags:
    flags = {
        "deleted": "\\Deleted",
        "draft": "\\Draft",
        "flagged": "\\Flagged",
        "recent": "\\Recent",
        "seen": "\\Seen",
        "answered": "\\Answered",
    }
    search_fields = {
        "id": "MESSAGE",
        "created": "DATE",
        "uid": "UID",
        "sender": "FROM",
        "to": "TO",
        "cc": "CC",
        "bcc": "BCC",
        "content": "TEXT",
        "size": "SIZE",
        "deleted": "\\Deleted",
        "draft": "\\Draft",
        "flagged": "\\Flagged",
        "recent": "\\Recent",
        "seen": "\\Seen",
        "subject": "SUBJECT",
        "answered": "\\Answered",
        "mime": None,
        "email": None,
        "attachments": None,
    }